version: '3'

services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    networks: 
      - webapp-network
    # depends_on:
    #   - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_DATABASE: webapp_db
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks: 
  #     - webapp-network

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks: 
      - webapp-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  webapp-network:
    external: true
